### ISSUE TITLE
View DE TE genes using IGV

### ISSUE THREAD

**Issue by Sidy2015** [mhammell-laboratory/TEtranscripts#142]
Hello, i used TEtranscripts to identify differentially expressed genes between two conditions. I have another ATAC-Seq. 
I wanted to dispay both RNASeq and ATACSeq data in IGV to check if Differentially expressed TE from the RNASeq correspond to open regions of the ATACSeq.
 I've tried to convert the Te gtf to a bed file and then extract a bed file  with the differentially Expressed TE but it doesn't work.
I'm aware of the fact that this issue may not be related to to the goal of this tool, but i am not a bioinformatician and i am new to TE analysis.
Thank you in advance for any suggestion.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
It is non-trivial to assess ATAC-seq data for TE, as most analyses depend on an "unambiguous" TE location (which is difficult given the difficulty of unambiguously aligning reads to repetitive sequences). Thus, `TEtranscripts` work by aggregating reads from TE subfamilies (i.e. copies of TE that come from the a particular TE consensus) in order to be able to do the differential analysis robustly.
Thus, if you try to extract a BED file of all the differentially expressed TE, you will get all the copies of each of them, which might includes copies that are themselves not differentially expressed (or not even expressed).

If you feel that you have a robust ATAC-seq analysis of your genome/TE regions, then you might want to try [TElocal](https://github.com/mhammell-laboratory/TElocal), which tries to perform analysis on each copy/instances of a TE in the genome. It might not be as robust as `TEtranscripts` (due to the difficulty in assessing each TE copy), and you would need to run your own differential analysis afterwards (e.g. DESeq2), but that might give you some idea of potential TE copies that might be differentially expressed (especially if the sub-family was found to be differentially expressed in `TEtranscripts`)

Hope this is helpful. Happy to answer more questions.

Thanks.

**Comment by Sidy2015** [comment]
Hi,

Thank you for help. I will try TElocal on my data as suggested
