### ISSUE TITLE
TEcount: does it count intronic TE?

### ISSUE THREAD

**Issue by ddepierre** [mhammell-laboratory/TEtranscripts#150]
Hi, 

The gene GTF that I use in as input of the --GTF i s a full GTF with genes, transcripts, exons, non coding, long non coding....
I was wondering if everything overlapping with any enter of my gene GTF is removed from TE reads quantif or is there a filter to avoid loosing TE overlapping with lncRNA or intronic TE ?

It is unclear to me if reads overlapping TE in introns are counts as  transcripts from TE in TEcount.
How can I be sure to include or exclude intronic TE?

Thanks, 
David

**Comment by olivertam** [comment]
Hi David,

Thanks for your interest in the software.
You are correct that there are a lot of lncRNA that could confound TE quantification. The approach that TEcount takes is as follows:
- If the read is unambiguously aligned to the genome (i.e. uniquely mapped), it will be assigned to a gene exon (and not introns).
- If the read aligned ambiguously (to multiple genomic location), it will be assigned to a TE subfamily (if available), then to a gene exon (if no overlapping TE found in any of the alignments). If there are multiple TE subfamilies that could be annotated, it will then be resolved in the EM step.

By default, intronic TE will be quantified as introns are not considered genic annotations. If you want to exclude intronic TE, then you would need to remove those entries from the TE GTF prior to running TEcount.
You could do the following (with [bedtools](https://bedtools.readthedocs.io/en/latest/):
```
$ awk '$3=="transcript"' [Gene GTF] > [Gene Transcript GTF]
$ intersectBed -v -a [TE GTF] -b [Gene Transcript GTF] > [no intronic TE GTF]
```

Let me know if you have other questions.
Thanks..

**Comment by olivertam** [comment]
Hi,

TEcount works on the GTF lines with "exon", so you can use a gene GTF with type=="gene" or type=="transcript", and converting that to "exon" to exclude any intronic TE. Here is a way to do it:
```
$ awk 'BEGIN{FS="\t";OFS="\t"};$3=="gene"{$3="exon";print}' [Gene GTF] > [Gene model GTF]
```

We typically allow up to 100 alignments to the genome, but exclude things that map more than that (since those are likely low complexity sequences).

You will still see some signal with uniquely mapped reads, as those there are a portion (up to 50%) that would align uniquely just to a TE (though that does include intronic TE). And yes, they will be biased towards those that have more alterations that make them more "mappable", and those less likely to be young/active.

Thanks.
