### ISSUE TITLE
Using TEtranscripts on data from rare disease patients

### ISSUE THREAD

**Issue by ChiaraF32** [mhammell-laboratory/TEtranscripts#153]
Hi,

I was just wondering if I can use your TEtranscripts tools to search for TE transcripts in patients affected with rare disease.

Would I just run the analysis using the patient RNAseq as the "treatment" sample and an age/tissue-matched control sample for "control"?

Thanks!
Chiara

**Comment by olivertam** [comment]
Hi Chiara,

Thank you for your interest in the software.
I think it's theoretically possible. However, it might be very difficult if you don't have many replicates, as most differential analyses need them to determine the expression variability within a group in order to better identify significant changes.

Thanks.
