### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by LIUXING-bio** [mhammell-laboratory/TEtranscripts#165]
Hi sir:
What kind of input file should it be? Is it possible for mRNA_seq?

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
TEtranscripts uses BAM files as input, and it is designed for bulk RNA-seq (total or mRNA). It is not designed for single-cell or single-nuclei RNA seq. You will also need a gene annotation GTF (typically obtained from Refseq, GENCODE or Ensembl), and a TE GTF (which we have generated for many [genome builds](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/))
Please let us know if this does not address your question.

Thanks

**Comment by 666lixiaona** [comment]
For  TE GTF (which we have generated for many [genome builds] your platform provide ,are they have the differences

**Comment by 666lixiaona** [comment]
HI,

<img width="1080" alt="屏幕截图 2024-02-14 201003" src="https://github.com/mhammell-laboratory/TEtranscripts/assets/160011681/4c3113d3-fd36-412e-9c73-70c168b2adaa">
I want to know  whether these profiles have the difference if I use them.

Thanks

**Comment by olivertam** [comment]
Hi,

If you are referring to the GTF from the same species (e.g. hg38, GRCh38_Ensembl and GRCh38_GENCODE), the difference is in the chromosome name for each of them. UCSC (hg38) has a `chr` in front of all their chromosome names (including scaffolds), while Ensembl (GRCh38_Ensembl) does not (e.g. `chr1` in hg38 is `1` in GRCh38). Since our program (and most other genome interval tools) are trying to match chromosomes by their name, you need to use the TE GTF that has the corresponding chromosome name/ID.
GENCODE is a mixed one, where canonical chromsomes has `chr` in front (e.g. `chr1`), but the scaffolds do not (and follow the Ensembl) nomenclature. Thus, if you're using GENCODE FASTA and gene GTF, you would need the GENCODE TE GTF for the quantification to work correctly.

Thanks.

**Comment by 666lixiaona** [comment]
Thank you very much.
