### ISSUE TITLE
Results  Gene counts total 0.0  Total annotated reads = 0

### ISSUE THREAD

**Issue by paulineBazelle** [mhammell-laboratory/TEtranscripts#169]
Hello, 
 I'm using TEcount on my data (which has been star mapped with Ensembl GrCH38). 
For TEcount I use : 
--TE: GRCh38_Ensembl_rmsk_TE.gtf.ind
--GTF: Homo_sapiens.GRCh38.110.gtf

For all my samples I get this result 

TE counts total 0.0
Gene counts total 0.0

Total annotated reads = 0
Total non-uniquely mapped reads = 731453
Total unannotated reads = 1001107

Is this normal? 

Thank you, 

Best, 
Pauline

**Comment by paulineBazelle** [comment]
HI,

Yes sure Thank you

[image: image.png]


Best,
Pauline

Le mar. 19 déc. 2023 à 09:00, Oliver Tam ***@***.***> a
écrit :

**Comment by olivertam** [comment]
Hi,

I'm afraid the image did not come through. Do you mind pasting the output?

Thanks.

**Comment by paulineBazelle** [comment]
Hi, 

@HD     VN:1.6  SO:coordinate
@SQ     SN:ENST00000473358      LN:712
@SQ     SN:ENST00000469289      LN:535
@SQ     SN:ENST00000417324      LN:1187
@SQ     SN:ENST00000461467      LN:590
@SQ     SN:ENST00000641515      LN:2618
@SQ     SN:ENST00000335137      LN:1054
@SQ     SN:ENST00000466430      LN:2748
@SQ     SN:ENST00000495576      LN:1319
@SQ     SN:ENST00000477740      LN:491

Thanks,
Pauline

**Comment by olivertam** [comment]
Hi,

It appears that you have mapped your reads onto the Ensembl transcripts (as shown by the `ENST` in the name), rather than the GRCh38 genome. Since `TEcount` uses genomic alignments to annotate against genes & TE, it will not work with this BAM file.
You will need to re-align with STAR onto the GRCh38 Ensembl genome in order to use `TEcount`.

Thanks.
