### ISSUE TITLE
GTF annotation to use for TE

### ISSUE THREAD

**Issue by sanhe374** [mhammell-laboratory/TEtranscripts#173]
I am using the Hg38 reference from UCSC: GCA_000001405.15_GRCh38_no_alt_analysis_set.fa and I was wondering which GTF annotation for TE I should be using together with this genome version?

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
It's unclear where you obtained that reference, as UCSC typically calls their file `hg38` (rather than `GRCh38`).
The best way to check is to look at the chromosome names in the FASTA file:
```
$ grep ">" GCA_000001405.15_GRCh38_no_alt_analysis_set.fa
```
If **all** chromosome names start with `chr`, then you should use the [hg38 one](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg38_rmsk_TE.gtf.gz)
If **none** of the chromosomes start with `chr`, then you should use the [GRCh38 Ensembl one](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCh38_Ensembl_rmsk_TE.gtf.gz)
If the canonical chromosomes (e.g. `chr1` to `chr22` & `chrX/Y/M`) starts with `chr`, but the others don't (e.g. `GL000256`), then you should use the [GRCh38 GENCODE one](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCh38_GENCODE_rmsk_TE.gtf.gz).

If none of them matches up, please let me know what I could download the file to take a closer look.

Thanks.

**Comment by sanhe374** [comment]
Thank you for your quick reply. It seems like all chromosomes start with chr so will use the hg38 one.
