### ISSUE TITLE
Question: different Genes/TEs expression

### ISSUE THREAD

**Issue by zhangqc723** [mhammell-laboratory/TEtranscripts#196]
Hi,

I have generated a counts table of TE_Genes using TEcounts. I then separately calculated differential expression for genes and TEs in R using DESeq2. Additionally, I calculated the differential expression of TE_Genes by using the merged counts table, as described in the TEtranscript documentation. However, the results from these two methods are different. Should I trust these results?

Thanks in advance for your response!

**Comment by olivertam** [comment]
Hi,

It is advisable to calculate differential expression of genes and TE together, as this allows a better estimation of dispersion given the assumption that most features are not expected to change significantly due to experimental condition. You would also ensure that the multiple testing correction (i.e. FDR) is correctly calculated for all the features, rather than calculated separately for genes and TE.

Thsnk.

**Comment by zhangqc723** [comment]
> Hi,
> 
> It is advisable to calculate differential expression of genes and TE together, as this allows a better estimation of dispersion given the assumption that most features are not expected to change significantly due to experimental condition. You would also ensure that the multiple testing correction (i.e. FDR) is correctly calculated for all the features, rather than calculated separately for genes and TE.
> 
> Thsnk.

Thank you for your insights.
