### ISSUE TITLE
Differences between featureCounts and TEtranscripts results

### ISSUE THREAD

**Issue by CSU-KangHu** [mhammell-laboratory/TEtranscripts#208]
Hi,

When I use `featureCounts` and `TEtranscripts` to quantify gene expression, I notice that their results are identical.

FeatureCounts:
![image](https://github.com/user-attachments/assets/7e529c5f-0094-4254-8dd8-ae3514e01c3c)

TEtranscripts:
![image](https://github.com/user-attachments/assets/8ef684ee-5ea0-4500-969e-c13266d72b51)

However, when quantifying LTR transposons, I observe a significant difference in their results. For example, with `featureCounts`, the count for `43-LTR_102-int` is 17919:
![image](https://github.com/user-attachments/assets/efdcfa7a-07a7-4d18-855d-c6b25dc6e375)

Whereas with `TEtranscripts`, the read count for `43-LTR_102-int` is only 138:
![image](https://github.com/user-attachments/assets/cce88507-2c00-4e2b-9f0f-7bb0e8653b8c)

Could you help me understand the cause of this discrepancy? It appears that `featureCounts` reports much higher counts for LTRs than `TEtranscripts`.

The command I used is:
```
TEcount -b ${bam_dir1}/SRX1734418/33.sha.output.sorted.bam --GTF ${gtf_dir}/33.sha.gtf --TE ${TE_dir}/33.sha.fa.gtf --sortByPos --project 33.sha
```

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.

The discrepancy depends on the command line that you used for `featureCounts`. If you're using the `-M` option to count multimapper reads, you should also set the `--fraction` to count each alignment hit as 1/x (where x is the number of genomic alignments for that read). Otherwise, you will double-count and thus inflate the count.

However, note that this will not replicate the `TEcount` results, as we perform the fractional count like `featureCount`, and then redistribute the read via an EM algorithm to get a better quantification of the TEs.

Please let me know if you have other questions.

Thanks.
