### ISSUE TITLE
0 count for TEs in all samples

### ISSUE THREAD

**Issue by HannahDixon** [mhammell-laboratory/TEtranscripts#72]
Hi, 

I am using your program to compare TE expression across samples. In my results however, I get 0 counts for TEs. When I visualise my bam files with the provided GTF file (for Drosophila) I see large coverage for many TEs. Do you know what the issue could be? I was wondering whether its with the bam files, I aligned them with Hisat2. 

Then the command I used for TEtranscripts was: 

> TEtranscripts --sortByPos --format BAM  --stranded reverse --mode multi  -t RNA.3.bam RNA.4.bam -c RNA.1.bam RNA.2.bam --GTF drosophila.gtf --TE dm6_rmsk_TE.gtf --project second_output

I tried both --mode uniq and --mode multi with the same results.

Here's some example output :
> uniq te counts = 0.0 
.......start iterative optimization .......... 
TE counts total 0.0 
Gene counts total 16918511.0 

> In library RNA.2.bam: 
Total annotated reads = 16918511.0 
Total non-uniquely mapped reads = 619791 
Total unannotated reads = 1443447 

On another note, I was wondering if you could advice me on how to build a GTF file for a species not provided by your lab. (Schizosaccharomyces pombe). 

Many thanks in advance, 

Hannah

**Comment by olivertam** [comment]
Hi Hannah,
Thanks for your interest in the software.
May I ask what your chromosome names are in your BAM and gene GTF file?
UCSC dm6 has a different chromosome name than BDGP, so that might be contributing to the zero counts in TE (since it's using the UCSC dm6 chromosome name).
For example: chr2L (dm6) is 2L (BDGP)
We have a [GTF](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/dm6_BDGP_rmsk_TE.gtf.gz) that would work with BDGP chromosome names, if that is the cause of the issue.
Thanks.

**Comment by HannahDixon** [comment]
Hi Oliver, 

Thank you for such a quick response.

My BAM files and gene GTF have BDGP chromosome names, and I used the TE GTF with UCSC names. Thank you so much for this! I will download the BDGP file now and try again. 

All the best

Hannah

**Comment by HannahDixon** [comment]
Hi Oliver, 

It worked fine with the correct TE GTF file. Thanks so much for your help.

Hannah
