### ISSUE TITLE
Question about use a subset of TE for quantification withTEtranscripts

### ISSUE THREAD

**Issue by MrMime007** [mhammell-laboratory/TEtranscripts#77]
Hello,

I have used TEtranscripts with TE annotation provided from your website,  the result shows the quantification of the whole TE family, the one TE I am interested in belongs to a family with more than 7000 members, I have validated the expression of this particular TE by qRT-PCR, however the TETranscripts result for the whole family shows opposite result. I'd like to know if there's any way to see the quantification for individual TE locus rather than the whole family?

Another question is I am only interested in a subset of TEs from different famailies, I'd like to know if I can generate the customized GTF file which only have annotation of these subset of TEs? If yes, do I need to change any parameters when I run TETranscripts?

Thank you very much for your help!

Best regards,

Bing

**Comment by olivertam** [comment]
Hi,

We would recommend trying [TElocal](https://github.com/mhammell-laboratory/TElocal) if you wish to quantify at the individual locus level.

It is possible to generate a customized GTF file using only a subset of TEs (you can select the ones you want from the full TE GTF). However, we would not recommend it because the redistribution assumes that all available annotations are used, and thus if a read maps to multiple TE, but only one (or a few) are in your custom TE annotation, it could erroneously mis-attribute the read.

Thanks.

**Comment by MrMime007** [comment]
Hello Dr. Tam,

Thank you very much for your reply and suggestions! I will use the full TE for TEtranscripts analysis.  I am trying to use TElocal, however, I cannot download prebuilt indices from this website(http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/), permission denied. Could you help me with this? By the way, I'd like to know TElocal is only for quantification or it can also perform differentiation expression analysis for TE? Thank you very much!

Best regards,

Bing

**Comment by MrMime007** [comment]
Hello Dr. Tam,

I forgot to mention in my previous message that it is the .locInd file for mm9 has problem, all the other files can be download. 

Thank you!

Best regards,

Bing

**Comment by olivertam** [comment]
Hi,

TElocal is only for quantification (similar to TEcount in the TEtranscripts package), since we feel that this is the most important step. We tend to use `DESeq2` for differential analysis, but you can use any differential analysis software that works with raw counts.
Thank you for pointing out the permission issue. This has been resolved.

Thanks again for your interest in the software.

**Comment by MrMime007** [comment]
Hello Dr. Tam,

Thanks for your suggestion! I have successfully downloaded mm9 .locInd file now. Thanks again for your helps!

Best regards,

Bing
