### ISSUE TITLE
Counting TEs in introns

### ISSUE THREAD

**Issue by mlizio** [mhammell-laboratory/TEtranscripts#81]
Hi, I have RNA-seq data from nuclear fractions. I quantify my gene expression by considering the whole gene, so if I want to use TEtranscripts with my gene annotation, what happens to TEs falling into introns? Will they contribute to the expression of both genes and TEs?

Would it be better to skip TEs in introns?

Thank you

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Working with nuclear fractions is certainly a difficult problem, and one that we are still wrapping our head around.
In its current form, it is not optimized for nuclear fractions precisely because of the presence of TE in introns. In order to capture intronic reads and assign them correctly, you will need to have a GTF where the entire transcript is considered an exon (similar to the approach that Cell Ranger does for single cell analysis, see [bottom of this page](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references).

However, the way that TEtranscripts treats intronic TE is that it will assign unambiguously mapped reads to the gene (intron), but ambiguously mapped reads to the TE. Thus, there's a possibility that a highly expressed gene with an intronic TE that is also present elsewhere to have reads assigned to the TE instead.

You can certainly remove intronic TE from your annotations. This might lead to an underestimation of TE reads (and overestimation of a gene read), but might be the best compromise.

This is still an active area of development, and hopefully we will have something that could better handle RNA-seq from nuclear fractions soon.

Thanks.
