### ISSUE TITLE
control samples

### ISSUE THREAD

**Issue by amitpande74** [mhammell-laboratory/TEtranscripts#94]
Dear Oliver,

I am trying to analyze this data set for human specific Alu expression[](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE120795).
However, the command line of your tool demands to have a control set as well. Can you kindly guide me as to what 
would be the apt control here.

warm regards

**Comment by olivertam** [comment]
Hi,

It really depends on your experiment. If you are just trying to quantify Alu expression, then I would recommend using TEcount, as you don't need to make any comparison (and thus no need for control).
Of course, if you're trying to assess differences in Alu expression, then you would probably need a sample that serves as your baseline. It would really depend on your experimental approach and question. If you want to describe your project in more detail, we might be able to see if there are apt controls out there for you.

Thanks.

**Comment by amitpande74** [comment]
Dear Oliver, 
Thanks for responding, although I thought TE local would fit the scheme of things.
But the project in a nutshell:
Human specific Alus I have (AluYa5, AluYb8 and AluYb9). I have evidence that they act as Enhancers. So took all tissue specific H3K4me1 from Human epigenome project. Observed that mostly all of them were enriched (when compared to other tissues) in the brain.
Now, wanted to map their expression from this study that I wrote to you (GSE120795). Then would come the network they control in the specific part of the human brain.
Hope it makes sense to your super brain, because I am not so good at writing things down.

warm regards,
Amit.

**Comment by olivertam** [comment]
Hi Amit,

Since you found enrichment of H3K4me1 in the brain compared to other tissues, you can probably use the other tissues as your control sample (and the brain as the treatment).
For example, if you found that the the human specific Alu elements were enriched most strongly in brain compared to liver, then you can run TEtranscripts with the brain RNAseq libraries as your treatment samples, and the liver ones as controls.
However, given that you're probably looking at specific loci of Alu, TElocal might be a better fit for you. In that case, you can run the differential analysis (e.g. using DESeq2) from the output of the TElocal (comparing brain to another tissue).
Let me know if that doesn't address your question.

Thanks.

**Comment by amitpande74** [comment]
Dear Oliver,
Thanks for your recommendations. Shall share my results with you once I am done processing the samples.
